### ISSUE TITLE
Consider having a separate style sheet for scalability  

### ISSUE THREAD

**Issue by leonelramos** [SkyanSam/SkyanSam.github.io#1]
Consider having a css folder where you keep all your styling for your website. Even though inline-css (css inside the html file) is a feature that is allowed, it is considered bad practice because it is not scalable. What I mean by scalable is that as your website grows and you need more styling for all the new pages and features, your html file will grow too large and will be hard to maintain. You can fix this by having all your css in a separate folder where it can be kept neat and where you will be able to easily reuse css for many pages instead of having to type new css for every html file. 

[check out this link for some help](https://www.webucator.com/how-to/how-create-css-external-style-sheet.cfm)

**Comment by SkyanSam** [comment]
Got it. Ill make sure to do that once I have more than one page. Ive done it before on my other website https://skyriftstudios.github.io/
But i understand what you are saying
